version: "3"
services:
    timescaledb:
        image: timescale/timescaledb:latest-pg14
        environment:
            TIMESCALEDB_TELEMETRY: "off"
            POSTGRES_PASSWORD: 'test'
            TCK_DB_PASSWORD: 'othertest'
        volumes:
            - ./db_init:/docker-entrypoint-initdb.d
            - db-data:/var/lib/postgresql/data
    nginx:
        image: nginx:latest
        volumes:
            - ./static:/usr/share/nginx/static:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./conf.d:/etc/nginx/conf.d:ro
            - ./certs:/etc/nginx/certs:ro
        ports:
            - "443:443"
    web:
        image: quartweb:latest
        build: ./web
        command: ["hypercorn", "web.server:app", "--config", "file:/opt/web/hcornconf.py"]

    app:
        image: fastapi-ts-app:latest
        environment:
            TCK_DB_PASSWORD: 'othertest'
            TCK_DB_LOGIN: "logs"
            TCK_DB_HOST: "timescaledb"
            TCK_ADMIN_LOGIN: 'admin'
            TCK_ADMIN_PASSWORD: 'admin'
            TCK_SECRET_KEY: 'b7340e05707526e43989a8c9ff17c0287e1e1751f3403e83dfc113c48d246ea8'
        build: .
        command:
            ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8181",
             "--ssl-keyfile=/opt/certs/localhost-key.pem",
             "--ssl-certfile=/opt/certs/localhost.pem"]

volumes:
    db-data:
        driver: local